language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE myapp_test;'
- echo "<?php $dbDsn = 'mysqli://travis@localhost/myapp_test';" > ./tests/config.php
install:
  - pear install Tree
script: pear run-tests -r
after_script:
- cat run-tests.log
